[package]
name = "rust-crafting-interpreters"
version = "0.1.0"
authors = ["akshay1992kalbhor <akshay1992kalbhor@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
